gtk-doc: Autospec creation for update from version 1.33.1 to version 1.33.2
Andre Klapper (1):
      Fix a typo in README

Niveditha Rau (3):
      Fix for NameError: name 'reduce' is not defined
      Fix for AttributeError: 'map' object has no attribute 'sort'
      Fix for TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

Simon McVittie (1):
      Implement a simple tree structure without using anytree